pragma Singleton

import QtQuick

Singleton {
    readonly property var categories: [
        { id: "bar", name: "Bar", exclusive: true },
        { id: "launcher", name: "Launcher", exclusive: true },
        { id: "notifications", name: "Notifications", exclusive: true },
        { id: "wallpaper", name: "Wallpaper", exclusive: true },
        { id: "lock", name: "Lock Screen", exclusive: true },
        { id: "idle", name: "Idle", exclusive: true },
        { id: "osd", name: "OSD", exclusive: true },
        { id: "control-center", name: "Control Center", exclusive: true },
        { id: "dock", name: "Dock", exclusive: true },
        { id: "power", name: "Power / Logout", exclusive: true },
        { id: "screenshot", name: "Screenshot", exclusive: true }
    ]

    // Software identity and capability identity are intentionally separate.
    // swaync is one installable package providing two capabilities.
    readonly property var providers: [
        { id: "bar.seashell", softwareId: "seashell", category: "bar", name: "Seashell Bar", description: "Native Seashell bar", builtIn: true, planned: false, packages: [], executable: "", processNames: [], configOwnership: "seashell-generated", supportsInstall: false, supportsUninstall: false, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: true, capabilities: ["bar"] },
        { id: "bar.waybar", softwareId: "waybar", category: "bar", name: "Waybar", description: "Customizable Wayland bar", builtIn: false, planned: false, packages: [{ name: "waybar" }], executable: "waybar", processNames: ["waybar"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: true, capabilities: ["bar"] },
        { id: "bar.ironbar", softwareId: "ironbar", category: "bar", name: "Ironbar", description: "GTK4 bar for Wayland compositors", builtIn: false, planned: false, packages: [{ name: "ironbar" }], executable: "ironbar", processNames: ["ironbar"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: false, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["bar"] },
        { id: "bar.nwg-panel", softwareId: "nwg-panel", category: "bar", name: "nwg-panel", description: "Panel for Sway and Hyprland", builtIn: false, planned: false, packages: [{ name: "nwg-panel" }], executable: "nwg-panel", processNames: ["nwg-panel"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: false, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["bar"] },

        { id: "launcher.seashell", softwareId: "seashell", category: "launcher", name: "Seashell Launcher", description: "Unified applications, actions, web apps and shortcuts", builtIn: true, planned: false, packages: [], executable: "", processNames: [], configOwnership: "seashell-generated", supportsInstall: false, supportsUninstall: false, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: true, capabilities: ["launcher"] },
        { id: "launcher.hyprlauncher", softwareId: "hyprlauncher", category: "launcher", name: "hyprlauncher", description: "Multipurpose launcher for Hyprland", builtIn: false, planned: false, packages: [{ name: "hyprlauncher" }], executable: "hyprlauncher", processNames: ["hyprlauncher"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["launcher"] },
        { id: "launcher.fuzzel", softwareId: "fuzzel", category: "launcher", name: "Fuzzel", description: "Wayland application launcher and picker", builtIn: false, planned: false, packages: [{ name: "fuzzel" }], executable: "fuzzel", processNames: ["fuzzel"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: true, capabilities: ["launcher"] },
        { id: "launcher.rofi", softwareId: "rofi", category: "launcher", name: "Rofi", description: "Rofi launcher with current Wayland support", builtIn: false, planned: false, packages: [{ name: "rofi" }], executable: "rofi", processNames: ["rofi"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: true, capabilities: ["launcher"] },
        { id: "launcher.wofi", softwareId: "wofi", category: "launcher", name: "Wofi", description: "Layer-shell launcher for wlroots", builtIn: false, planned: false, packages: [{ name: "wofi" }], executable: "wofi", processNames: ["wofi"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: true, capabilities: ["launcher"] },

        { id: "notifications.seashell", softwareId: "seashell", category: "notifications", name: "Seashell Notifications", description: "Native notifications are not implemented", builtIn: true, planned: true, packages: [], executable: "", processNames: [], configOwnership: "none", supportsInstall: false, supportsUninstall: false, supportsActivation: false, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["notifications"] },
        { id: "notifications.mako", softwareId: "mako", category: "notifications", name: "Mako", description: "Wayland notification daemon", builtIn: false, planned: false, packages: [{ name: "mako" }], executable: "mako", processNames: ["mako"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: false, capabilities: ["notifications"] },
        { id: "notifications.swaync", softwareId: "swaync", category: "notifications", name: "SwayNotificationCenter", description: "Notifications and notification center", builtIn: false, planned: false, packages: [{ name: "swaync" }], executable: "swaync", processNames: ["swaync"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: false, capabilities: ["notifications", "control-center"] },
        { id: "notifications.dunst", softwareId: "dunst", category: "notifications", name: "Dunst", description: "Notification daemon with Wayland support", builtIn: false, planned: false, packages: [{ name: "dunst" }], executable: "dunst", processNames: ["dunst"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: false, capabilities: ["notifications"] },

        { id: "wallpaper.seashell", softwareId: "seashell", category: "wallpaper", name: "Seashell Wallpaper", description: "Native wallpaper selection and theme integration", builtIn: true, planned: false, packages: [], executable: "", processNames: [], configOwnership: "seashell-generated", supportsInstall: false, supportsUninstall: false, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: true, capabilities: ["wallpaper"] },
        { id: "wallpaper.hyprpaper", softwareId: "hyprpaper", category: "wallpaper", name: "hyprpaper", description: "Hyprland wallpaper daemon", builtIn: false, planned: false, packages: [{ name: "hyprpaper" }], executable: "hyprpaper", processNames: ["hyprpaper"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: false, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["wallpaper"] },
        { id: "wallpaper.awww", softwareId: "awww", category: "wallpaper", name: "awww", description: "Animated Wayland wallpaper daemon", builtIn: false, planned: false, packages: [{ name: "awww" }], executable: "awww-daemon", processNames: ["awww-daemon"], configOwnership: "none", supportsInstall: true, supportsUninstall: true, supportsActivation: false, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["wallpaper"] },
        { id: "wallpaper.swaybg", softwareId: "swaybg", category: "wallpaper", name: "swaybg", description: "Simple Wayland background process using Seashell's selected wallpaper", builtIn: false, planned: false, packages: [{ name: "swaybg" }], executable: "swaybg", processNames: ["swaybg"], configOwnership: "none", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: false, supportsThemeSync: false, capabilities: ["wallpaper"] },

        { id: "lock.seashell", softwareId: "seashell", category: "lock", name: "Seashell Lock Screen", description: "No built-in lock screen", builtIn: true, planned: true, packages: [], executable: "", processNames: [], configOwnership: "none", supportsInstall: false, supportsUninstall: false, supportsActivation: false, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["lock"] },
        { id: "lock.hyprlock", softwareId: "hyprlock", category: "lock", name: "hyprlock", description: "Hyprland screen locker", builtIn: false, planned: false, packages: [{ name: "hyprlock" }], executable: "hyprlock", processNames: ["hyprlock"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["lock"] },
        { id: "lock.swaylock", softwareId: "swaylock", category: "lock", name: "swaylock", description: "Wayland session locker", builtIn: false, planned: false, packages: [{ name: "swaylock" }], executable: "swaylock", processNames: ["swaylock"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["lock"] },
        { id: "lock.gtklock", softwareId: "gtklock", category: "lock", name: "gtklock", description: "GTK Wayland screen locker", builtIn: false, planned: false, packages: [{ name: "gtklock" }], executable: "gtklock", processNames: ["gtklock"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["lock"] },

        { id: "idle.hypridle", softwareId: "hypridle", category: "idle", name: "hypridle", description: "Hyprland idle daemon; lock timeout invokes Seashell's selected lock action", builtIn: false, planned: false, packages: [{ name: "hypridle" }], executable: "hypridle", processNames: ["hypridle"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: false, capabilities: ["idle"] },
        { id: "idle.swayidle", softwareId: "swayidle", category: "idle", name: "swayidle", description: "Idle management; lock timeout invokes Seashell's selected lock action", builtIn: false, planned: false, packages: [{ name: "swayidle" }], executable: "swayidle", processNames: ["swayidle"], configOwnership: "seashell-generated", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: false, capabilities: ["idle"] },

        { id: "osd.seashell", softwareId: "seashell", category: "osd", name: "Seashell OSD", description: "No built-in OSD", builtIn: true, planned: true, packages: [], executable: "", processNames: [], configOwnership: "none", supportsInstall: false, supportsUninstall: false, supportsActivation: false, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["osd"] },
        { id: "osd.swayosd", softwareId: "swayosd", category: "osd", name: "SwayOSD", description: "On-screen display server for wlroots", builtIn: false, planned: false, packages: [{ name: "swayosd" }], executable: "swayosd-server", processNames: ["swayosd-server"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: false, capabilities: ["osd"] },
        { id: "osd.wob", softwareId: "wob", category: "osd", name: "wob", description: "Wayland overlay bar for piped volume or brightness values", builtIn: false, planned: false, packages: [{ name: "wob" }], executable: "wob", processNames: ["wob"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: false, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["osd"] },

        { id: "control-center.seashell", softwareId: "seashell", category: "control-center", name: "Seashell Control Center", description: "No dedicated control center", builtIn: true, planned: true, packages: [], executable: "", processNames: [], configOwnership: "none", supportsInstall: false, supportsUninstall: false, supportsActivation: false, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["control-center"] },
        { id: "control-center.swaync", softwareId: "swaync", category: "control-center", name: "SwayNotificationCenter", description: "Shares the SwayNC notification daemon and installation", builtIn: false, planned: false, packages: [{ name: "swaync" }], executable: "swaync-client", processNames: ["swaync"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: false, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["control-center"] },

        { id: "dock.seashell", softwareId: "seashell", category: "dock", name: "Seashell Dock", description: "No built-in dock", builtIn: true, planned: true, packages: [], executable: "", processNames: [], configOwnership: "none", supportsInstall: false, supportsUninstall: false, supportsActivation: false, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["dock"] },
        { id: "dock.nwg-dock-hyprland", softwareId: "nwg-dock-hyprland", category: "dock", name: "nwg-dock-hyprland", description: "Dock designed for Hyprland", builtIn: false, planned: false, packages: [{ name: "nwg-dock-hyprland" }], executable: "nwg-dock-hyprland", processNames: ["nwg-dock-hyprland"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: true, supportsSettings: true, supportsThemeSync: false, capabilities: ["dock"] },

        { id: "power.seashell", softwareId: "seashell", category: "power", name: "Seashell Power Menu", description: "No built-in power menu", builtIn: true, planned: true, packages: [], executable: "", processNames: [], configOwnership: "none", supportsInstall: false, supportsUninstall: false, supportsActivation: false, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["power"] },
        { id: "power.wlogout", softwareId: "wlogout", category: "power", name: "wlogout", description: "Wayland logout and session menu", builtIn: false, planned: false, packages: [{ name: "wlogout" }], executable: "wlogout", processNames: ["wlogout"], configOwnership: "external-user-config", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: true, supportsThemeSync: false, capabilities: ["power"] },

        { id: "screenshot.hyprshot", softwareId: "hyprshot", category: "screenshot", name: "hyprshot", description: "Screenshot utility for Hyprland", builtIn: false, planned: false, packages: [{ name: "hyprshot" }], executable: "hyprshot", processNames: ["hyprshot"], configOwnership: "none", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["screenshot"] },
        { id: "screenshot.grim", softwareId: "grim-slurp", category: "screenshot", name: "grim + slurp", description: "Wayland screenshot with region picker", builtIn: false, planned: false, packages: [{ name: "grim" }, { name: "slurp" }], executable: "grim", processNames: ["grim"], configOwnership: "none", supportsInstall: true, supportsUninstall: true, supportsActivation: true, supportsLifecycle: false, supportsSettings: false, supportsThemeSync: false, capabilities: ["screenshot"] }
    ]

    function category(id) { return categories.find(item => item.id === id) }
    function providersFor(categoryId) { return providers.filter(item => item.category === categoryId) }
    function provider(id) { return providers.find(item => item.id === id) }
    function softwareProviders(softwareId) { return providers.filter(item => item.softwareId === softwareId) }
}
